name: Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker_hub_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t dhruv898002/vid-time .
          docker push dhruv898002/vid-time

  deploy_to_lightsail:
    runs-on: ubuntu-latest

    needs: docker_hub_push

    steps:
      - name: Deploy to AWS Lightsail
        run: |
          # Use AWS CLI or other tools to deploy your Docker image to Lightsail
          # Example: aws lightsail push-container-image --service-name your-lightsail-service --label your-image-name
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
