name: Dev CI/CD

on:
  push:
    branches:
      - dev

jobs:
  docker_hub_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t dhruv898002/vid-time .
          docker push dhruv898002/vid-time

  deploy_to_lightsail:
    runs-on: ubuntu-latest

    needs: docker_hub_push

    steps:
      - name: SSH Agent Action
        uses: truemark/ssh-agent-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Lightsail
        run: |
          ssh openstack@15.157.4.6 'echo "hello how are you from lighsail--------------" '
