name: prod CI/CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  linting:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  testing:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd back-end
          npm install
          npm run test

  docker_hub_push:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t dhruv898002/vid-time .
          docker push dhruv898002/vid-time

  deploy_lightsail:
    runs-on: ubuntu-latest
    needs: docker_hub_push
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 15.157.146.40
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -q)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)
            docker pull dhruv898002/vid-time:latest
            docker run -d -p 80:3000 dhruv898002/vid-time
